---
- name: Template the systemd unit
  ansible.builtin.template:
    src: service.j2
    dest: "{{ nocloud_metadata_server_systemd_service_file_path }}"
    owner: "root"
    mode: 0755
  register: _nocloud_systemd_template

- name: Reload systemd if needed
  ansible.builtin.systemd:
    daemon_reload: true
  when: _nocloud_systemd_template.changed

- name: Start the service
  ansible.builtin.systemd:
    name: "{{ nocloud_metadata_server_systemd_service_name }}.service"
    state: started
    enabled: true

- name: Restart the service if needed
  ansible.builtin.systemd:
    name: "{{ nocloud_metadata_server_systemd_service_name }}.service"
    state: restarted
  when: _nocloud_systemd_template.changed or _nocloud_binary.changed

- name: Reload the config if needed
  ansible.builtin.systemd:
    name: "{{ nocloud_metadata_server_systemd_service_name }}.service"
    state: reloaded
  when: _nocloud_config.changed
