---
- name: Template the systemd unit
  ansible.builtin.template:
    src: service.j2
    dest: "{{ nocloud_metadata_server_systemd_service_file_path }}"
    owner: "root"
    mode: 0755
  register: _nocloud_systemd_template

- name: Reload systemd if needed
  ansible.builtin.systemd:
    daemon_reload: true
  when: _nocloud_systemd_template.changed

- name: Enable the service
  ansible.builtin.systemd:
    name: "{{ nocloud_metadata_server_systemd_service_name }}.service"
    state: >-
      {{
        _nocloud_systemd_template.changed
        or _nocloud_binary.changed
        or _nocloud_config.changed
        | ternary('restarted', 'started')
      }}
    enabled: true
