---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: registry.hub.docker.com/geerlingguy/docker-debian11-ansible:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
